AWSTemplateFormatVersion: 2010-09-09
Description: Creates a RDS Aurora cluster.
Parameters:
    DatabaseInstanceType:
        Default: db.t2.small
        AllowedValues:
            - db.t2.small
            - db.t2.medium
        Description: The instance type to use for the database.
        Type: String
    DatabasePassword:
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters.
        Description: The database admin account password.
        MaxLength: '30'
        MinLength: '8'
        NoEcho: 'true'
        Type: String
    DatabaseUsername:
        AllowedPattern: "[a-zA-Z0-9]+"
        ConstraintDescription: must contain only alphanumeric characters.
        Description: The database admin account user name.
        MaxLength: '16'
        MinLength: '1'
        Type: String
    DatabaseBackupRetentionPeriod:
        Type: String
        Default: 1
        AllowedValues:
            - 1
            - 10
            - 20
        Description: The database backup retention period in days.
    DatabaseSubnets:
        Description: The subnets to place database instances in.
        Type: List<String>
    VPCId:
        Type: String
        Description: VPC in which to launch the Aurora RDS Cluster.
Resources:
    DBSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow Inbound Traffic to DB
            VpcId:
                Ref: VPCId
            SecurityGroupIngress:
                - IpProtocol: tcp
                  FromPort: '3306'
                  ToPort: '3306'
                  CidrIp: 0.0.0.0/0
    StackAlarmTopic:
        Type: AWS::SNS::Topic
        Properties:
            DisplayName: Stack Alarm Topic
    DatabaseSubnetGroup:
        Type: AWS::RDS::DBSubnetGroup
        Properties:
            DBSubnetGroupDescription: CloudFormation managed DB subnet group.
            SubnetIds:
                Ref: DatabaseSubnets
    DatabaseCluster:
        Type: AWS::RDS::DBCluster
        Properties:
            Engine: aurora
            MasterUsername:
                Ref: DatabaseUsername
            MasterUserPassword:
                Ref: DatabasePassword
            BackupRetentionPeriod:
                Ref: DatabaseBackupRetentionPeriod
            PreferredBackupWindow: 01:00-02:30
            PreferredMaintenanceWindow: mon:03:00-mon:04:00
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
            VpcSecurityGroupIds:
                - Ref: DBSecurityGroup
            StorageEncrypted : true
    DatabasePrimaryInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            Engine: aurora
            DBClusterIdentifier:
                Ref: DatabaseCluster
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
            StorageEncrypted: true
            PubliclyAccessible: true
    DatabaseReplicaInstance:
        Type: AWS::RDS::DBInstance
        Properties:
            Engine: aurora
            DBClusterIdentifier:
                Ref: DatabaseCluster
            DBInstanceClass:
                Ref: DatabaseInstanceType
            DBSubnetGroupName:
                Ref: DatabaseSubnetGroup
            StorageEncrypted: true
            PubliclyAccessible: true
    DatabasePrimaryCPUAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Primary database CPU utilization is over 80%.
            Namespace: AWS/RDS
            MetricName: CPUUtilization
            Unit: Percent
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabasePrimaryInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic
    DatabaseReplicaCPUAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Replica database CPU utilization is over 80%.
            Namespace: AWS/RDS
            MetricName: CPUUtilization
            Unit: Percent
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 80
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseReplicaInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic
    DatabasePrimaryMemoryAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Primary database freeable memory is under 350MB.
            Namespace: AWS/RDS
            MetricName: FreeableMemory
            Unit: Bytes
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 350000000
            ComparisonOperator: LessThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabasePrimaryInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic
    DatabasePrimaryMemoryAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Replica database freeable memory is under 350MB.
            Namespace: AWS/RDS
            MetricName: FreeableMemory
            Unit: Bytes
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 350000000
            ComparisonOperator: LessThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseReplicaInstance
            AlarmActions:
                - Ref: StackAlarmTopic
            InsufficientDataActions:
                - Ref: StackAlarmTopic
    DatabasePrimaryReplicationAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Database replication latency is over 200ms.
            Namespace: AWS/RDS
            MetricName: AuroraReplicaLag
            Unit: Milliseconds
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 200
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseReplicaInstance
            AlarmActions:
                - Ref: StackAlarmTopic
    DatabaseReplicaReplicationAlarm:
        Type: AWS::CloudWatch::Alarm
        Properties:
            AlarmDescription: Database replication latency is over 200ms.
            Namespace: AWS/RDS
            MetricName: AuroraReplicaLag
            Unit: Milliseconds
            Statistic: Average
            Period: 300
            EvaluationPeriods: 2
            Threshold: 200
            ComparisonOperator: GreaterThanOrEqualToThreshold
            Dimensions:
                - Name: DBInstanceIdentifier
                  Value:
                      Ref: DatabaseReplicaInstance
            AlarmActions:
                - Ref: StackAlarmTopic
Outputs:
    AuroraEndpoint:
      Value: !GetAtt DatabaseCluster.Endpoint.Address
      Description: 'Aurora Endpoint address'
      Export:
        Name: !Join [ ":", [ !Ref "AWS::StackName", '-WebAnalyticsAurora' ] ]
    DBClusterId:
      Value: !Ref DatabaseCluster
    PrimaryInstanceId:
      Value: !Ref DatabasePrimaryInstance